import React from 'react'

const styles: Record<string, React.CSSProperties> = {
  container: { minHeight: '100vh', background: '#f8fafc', fontFamily: 'system-ui, sans-serif' },
  topBar: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 24px', background: '#fff', borderBottom: '1px solid #e5e7eb', boxShadow: '0 1px 3px rgba(0,0,0,0.05)', position: 'sticky', top: 0, zIndex: 10 },
  topLeft: { display: 'flex', alignItems: 'center', gap: 14 },
  topRight: { display: 'flex', gap: 10, alignItems: 'center' },
  backBtn: { display: 'flex', alignItems: 'center', gap: 4, background: 'none', border: 'none', color: '#6b7280', cursor: 'pointer', fontSize: 13, padding: '4px 8px', borderRadius: 6 },
  title: { fontWeight: 800, fontSize: 18, color: '#0f766e', letterSpacing: -0.5 },
  navBtn: { display: 'flex', alignItems: 'center', gap: 6, padding: '7px 14px', borderRadius: 8, border: '1px solid #d1d5db', background: '#fff', cursor: 'pointer', fontSize: 13, fontWeight: 600 },
  content: { maxWidth: 1000, margin: '0 auto', padding: '28px 24px' },
  center: { display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: 200 },
  section: { display: 'flex', flexDirection: 'column', gap: 18 },
  sectionHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  sectionTitle: { fontSize: 18, fontWeight: 800, color: '#111', letterSpacing: -0.3 },
  statsRow: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))', gap: 14, marginBottom: 8 },
  statCard: { background: '#fff', border: '1px solid #e5e7eb', borderRadius: 10, padding: '16px 18px', textAlign: 'center' },
  statValue: { fontSize: 28, fontWeight: 800, color: '#111', letterSpacing: -1 },
  statLabel: { fontSize: 12, color: '#6b7280', marginTop: 2 },
  batchList: { display: 'flex', flexDirection: 'column', gap: 8 },
  batchRow: { display: 'flex', alignItems: 'center', gap: 0, background: '#fff', border: '1px solid #e5e7eb', borderRadius: 10, overflow: 'hidden', cursor: 'pointer', transition: 'box-shadow 0.15s' },
  batchAccent: { width: 5, alignSelf: 'stretch', flexShrink: 0 },
  batchInfo: { flex: 1, padding: '14px 16px', display: 'flex', flexDirection: 'column', gap: 5 },
  batchName: { fontWeight: 700, fontSize: 15, color: '#111' },
  batchMeta: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 10 },
  metaText: { fontSize: 12, color: '#6b7280' },
  badge: { display: 'inline-flex', alignItems: 'center', fontSize: 11, fontWeight: 700, padding: '3px 10px', borderRadius: 20, background: '#f3f4f6', color: '#374151' },
  statusPill: { fontSize: 12, fontWeight: 700, padding: '4px 14px', borderRadius: 20, border: '1.5px solid', marginRight: 14, whiteSpace: 'nowrap' as const },
  empty: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: '48px 0', color: '#9ca3af' },
  formGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18 },
  formGroup: { display: 'flex', flexDirection: 'column', gap: 6 },
  label: { fontSize: 13, fontWeight: 600, color: '#374151' },
  hint: { fontSize: 11, fontWeight: 400, color: '#9ca3af' },
  input: { padding: '9px 12px', border: '1px solid #d1d5db', borderRadius: 8, fontSize: 14, outline: 'none' },
  select: { padding: '9px 12px', border: '1px solid #d1d5db', borderRadius: 8, fontSize: 14, background: '#fff' },
  textarea: { padding: '9px 12px', border: '1px solid #d1d5db', borderRadius: 8, fontSize: 14, resize: 'vertical' as const, fontFamily: 'inherit' },
  chipRow: { display: 'flex', flexWrap: 'wrap', gap: 8, alignItems: 'center' },
  chip: { padding: '5px 14px', borderRadius: 20, border: '1.5px solid #d1d5db', background: '#fff', cursor: 'pointer', fontSize: 13, fontWeight: 600 },
  chipActive: { padding: '5px 14px', borderRadius: 20, border: '1.5px solid #0f766e', background: '#ccfbf1', color: '#0f766e', cursor: 'pointer', fontSize: 13, fontWeight: 700 },
  actionRow: { display: 'flex', flexWrap: 'wrap', gap: 10 },
  primaryBtn: { display: 'inline-flex', alignItems: 'center', gap: 6, padding: '9px 18px', background: '#0f766e', color: '#fff', border: 'none', borderRadius: 8, cursor: 'pointer', fontSize: 13, fontWeight: 700 },
  outlineBtn: { display: 'inline-flex', alignItems: 'center', gap: 6, padding: '8px 16px', background: '#fff', color: '#374151', border: '1.5px solid #d1d5db', borderRadius: 8, cursor: 'pointer', fontSize: 13, fontWeight: 600 },
  destructiveBtn: { display: 'inline-flex', alignItems: 'center', gap: 6, padding: '9px 18px', background: '#dc2626', color: '#fff', border: 'none', borderRadius: 8, cursor: 'pointer', fontSize: 13, fontWeight: 700 },
  destructiveOutlineBtn: { display: 'inline-flex', alignItems: 'center', gap: 6, padding: '8px 16px', background: '#fff', color: '#dc2626', border: '1.5px solid #fca5a5', borderRadius: 8, cursor: 'pointer', fontSize: 13, fontWeight: 600 },
  warningBtn: { display: 'inline-flex', alignItems: 'center', gap: 6, padding: '9px 18px', background: '#d97706', color: '#fff', border: 'none', borderRadius: 8, cursor: 'pointer', fontSize: 13, fontWeight: 700 },
  infoBox: { background: '#f0fdfa', border: '1px solid #99f6e4', borderRadius: 8, padding: '12px 16px', fontSize: 13, color: '#134e4a' },
  warnBox: { background: '#fffbeb', border: '1px solid #fcd34d', borderRadius: 8, padding: '12px 16px', fontSize: 13, color: '#78350f' },
  helpText: { fontSize: 13, color: '#6b7280', lineHeight: 1.6, margin: 0 },
  table: { background: '#fff', border: '1px solid #e5e7eb', borderRadius: 10, overflow: 'hidden' },
  tableHeader: { display: 'grid', gridTemplateColumns: '2fr 1fr 1fr 1fr', padding: '10px 16px', background: '#f9fafb', fontSize: 11, fontWeight: 700, color: '#6b7280', textTransform: 'uppercase' as const, letterSpacing: 0.5, borderBottom: '1px solid #e5e7eb' },
  tableRow: { display: 'grid', gridTemplateColumns: '2fr 1fr 1fr 1fr', padding: '12px 16px', borderBottom: '1px solid #f3f4f6', fontSize: 13, alignItems: 'center' },
  chartDetail: { background: '#f9fafb', borderTop: '1px solid #e5e7eb', padding: '8px 16px 8px 32px', display: 'flex', flexDirection: 'column', gap: 6 },
  chartDetailRow: { display: 'flex', flexWrap: 'wrap', alignItems: 'flex-start', gap: 12, padding: '6px 0', borderBottom: '1px solid #e5e7eb' },
  fbList: { width: '100%', display: 'flex', flexDirection: 'column', gap: 3, marginTop: 4 },
  fbRow: { display: 'flex', flexWrap: 'wrap', gap: 8, alignItems: 'center', padding: '3px 0' },
  fbSection: { fontSize: 11, fontWeight: 700, background: '#dbeafe', color: '#1d4ed8', padding: '2px 8px', borderRadius: 10 },
  fbIssue: { fontSize: 11, fontWeight: 700, background: '#fee2e2', color: '#dc2626', padding: '2px 8px', borderRadius: 10 },
  drgCard: { background: '#fff', border: '1.5px solid #e5e7eb', borderRadius: 10, padding: 18, display: 'flex', flexDirection: 'column', gap: 12 },
  drgHeader: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 12 },
  drgActions: { display: 'flex', gap: 12 },
  coderTable: { border: '1px solid #d1fae5', borderRadius: 8, overflow: 'hidden', marginTop: 8 },
  coderTableHeader: { display: 'grid', gridTemplateColumns: '1fr 140px 32px', padding: '8px 14px', background: '#f0fdf4', fontSize: 11, fontWeight: 700, color: '#065f46', textTransform: 'uppercase' as const, letterSpacing: 0.5, borderBottom: '1px solid #d1fae5' },
  coderTableRow: { display: 'grid', gridTemplateColumns: '1fr 140px 32px', padding: '8px 14px', borderBottom: '1px solid #f0fdf4', fontSize: 13, alignItems: 'center' },
  removeCoder: { border: 'none', background: 'none', cursor: 'pointer', color: '#9ca3af', fontSize: 14, padding: 0, lineHeight: 1 },
  modeToggle: { display: 'flex', border: '1px solid #e5e7eb', borderRadius: 7, overflow: 'hidden' },
  modeTab: { padding: '5px 14px', border: 'none', background: '#fff', fontSize: 12, fontWeight: 600, color: '#6b7280', cursor: 'pointer' },
  modeTabActive: { padding: '5px 14px', border: 'none', background: '#4f46e5', fontSize: 12, fontWeight: 600, color: '#fff', cursor: 'pointer' },
  chartPickerHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  chartSearchRow: { display: 'flex', gap: 8, alignItems: 'center', marginBottom: 10, flexWrap: 'wrap' as const },
  chartPickerList: { border: '1px solid #e5e7eb', borderRadius: 8, overflow: 'hidden', maxHeight: 320, overflowY: 'auto' as const },
  chartPickerListHeader: { display: 'grid', gridTemplateColumns: '110px 1fr 120px 32px', padding: '7px 14px', background: '#f9fafb', fontSize: 11, fontWeight: 700, color: '#6b7280', textTransform: 'uppercase' as const, letterSpacing: 0.5, borderBottom: '1px solid #e5e7eb', position: 'sticky' as const, top: 0 },
  chartPickerRow: { display: 'grid', gridTemplateColumns: '110px 1fr 120px 32px', padding: '9px 14px', borderBottom: '1px solid #f3f4f6', fontSize: 13, alignItems: 'center', cursor: 'pointer' },
  chartPickerNum: { fontWeight: 700, color: '#1e40af' },
  chartPickerCat: { color: '#374151' },
  chartPickerDiff: { color: '#6b7280', fontSize: 12 },
  clearSmallBtn: { border: 'none', background: 'none', color: '#dc2626', fontSize: 12, cursor: 'pointer', padding: 0 },
  quickAddRow: { display: 'flex', gap: 8, alignItems: 'center', marginBottom: 8 },
  configSection: { background: '#fff', border: '1px solid #e5e7eb', borderRadius: 10, padding: '16px 18px', display: 'flex', flexDirection: 'column', gap: 10 },
  configSectionTitle: { fontSize: 14, fontWeight: 700, color: '#111' },
  weightGrid: { display: 'flex', gap: 16, flexWrap: 'wrap' as const },
  methodOption: { display: 'flex', alignItems: 'flex-start', gap: 10, cursor: 'pointer', padding: '10px 12px', background: '#f9fafb', borderRadius: 8, border: '1px solid #e5e7eb' },
  methodLabel: { fontSize: 13, fontWeight: 700, color: '#111', display: 'flex', alignItems: 'center', gap: 8 },
  methodBadge: { fontSize: 10, fontWeight: 700, background: '#d1fae5', color: '#065f46', padding: '2px 8px', borderRadius: 10, letterSpacing: 0.3 },
  methodDesc: { fontSize: 12, color: '#6b7280', marginTop: 2, lineHeight: 1.5 },
  dpoPanel: { background: '#eff6ff', border: '1px solid #bfdbfe', borderRadius: 8, padding: '12px 16px', marginBottom: 10 },
  dpoPanelTitle: { fontSize: 12, fontWeight: 700, color: '#1d4ed8', marginBottom: 10, display: 'flex', alignItems: 'center', gap: 8 },
  dpoSupBadge: { fontSize: 10, fontWeight: 700, background: '#dbeafe', color: '#1d4ed8', padding: '2px 8px', borderRadius: 10, letterSpacing: 0.3 },
  dpoPanelRow: { display: 'flex', alignItems: 'center', gap: 20, flexWrap: 'wrap' as const },
  dpoDivider: { width: 1, height: 36, background: '#bfdbfe', margin: '0 4px' },
  cycleSection: { background: '#fff', border: '1px solid #e5e7eb', borderRadius: 10, padding: '16px 18px', display: 'flex', flexDirection: 'column', gap: 8 },
  cycleRow: { display: 'flex', alignItems: 'center', gap: 12, padding: '10px 12px', background: '#f9fafb', borderRadius: 8, border: '1px solid #e5e7eb' },
  cycleBadge: { fontSize: 11, fontWeight: 800, background: '#dbeafe', color: '#1d4ed8', padding: '3px 10px', borderRadius: 20, whiteSpace: 'nowrap' as const },
  allocationPanel: { background: '#f0fdf4', border: '1.5px solid #86efac', borderRadius: 10, padding: '16px 18px', marginBottom: 10 },
  noteRow: { display: 'flex', alignItems: 'flex-start', gap: 12, padding: '8px 0', borderBottom: '1px solid #f3f4f6', fontSize: 13 },
  emptyState: { fontSize: 13, color: '#9ca3af', padding: '20px 0', textAlign: 'center' as const },
  dropzone: { border: '2px dashed #d1d5db', borderRadius: 10, padding: '28px 20px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8, cursor: 'pointer', background: '#fafafa' },
}

export default styles
