import { useState, useEffect } from 'react'
import { Download, Trash2, RefreshCw } from 'lucide-react'
import toast from 'react-hot-toast'
import { listAssessmentHistory, exportAssessmentPDF, exportAnswerKey } from '../../api'

interface AssessmentRecord {
  id: number
  assessment_name: string
  config_name: string | null
  student_count: number
  questions_per_student: number
  generated_by: string
  generated_at: string | null
}

export function AssessmentHistoryView() {
  const [records, setRecords] = useState<AssessmentRecord[]>([])
  const [loading, setLoading] = useState(true)
  const [deletingId, setDeletingId] = useState<number | null>(null)
  const [confirmDelete, setConfirmDelete] = useState<number | null>(null)
  const [passphrase, setPassphrase] = useState('')

  function load() {
    setLoading(true)
    listAssessmentHistory()
      .then(setRecords)
      .catch(() => toast.error('Failed to load history'))
      .finally(() => setLoading(false))
  }

  useEffect(() => { load() }, [])

  async function handleDelete(id: number) {
    if (!passphrase.trim()) { toast.error('Enter passphrase'); return }
    setDeletingId(id)
    try {
      await fetch(`${import.meta.env.VITE_API_URL || '/api'}/assessment/${id}?passphrase=${encodeURIComponent(passphrase)}`, {
        method: 'DELETE',
      }).then(async r => {
        if (!r.ok) {
          const data = await r.json()
          throw new Error(data.detail || 'Delete failed')
        }
        return r.json()
      })
      toast.success('Assessment deleted')
      setConfirmDelete(null)
      setPassphrase('')
      load()
    } catch (e: unknown) {
      const err = e as Error
      toast.error(err.message || 'Delete failed')
    } finally {
      setDeletingId(null)
    }
  }

  if (loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', padding: 60 }}>
        <RefreshCw size={18} style={{ animation: 'spin 1s linear infinite', color: '#6b7280' }} />
      </div>
    )
  }

  return (
    <div>
      {records.length === 0 ? (
        <div style={styles.empty}>No assessments generated yet. Go to Generate tab to create your first assessment.</div>
      ) : (
        <div style={styles.tableWrap}>
          <table style={styles.table}>
            <thead>
              <tr style={styles.thead}>
                {['Name', 'Config', 'Date', 'Generated By', 'Students', 'Questions', 'Actions'].map(h => (
                  <th key={h} style={styles.th}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {records.map(r => (
                <tr key={r.id} style={styles.tr}>
                  <td style={{ ...styles.td, fontWeight: 700 }}>{r.assessment_name}</td>
                  <td style={{ ...styles.td, color: '#9ca3af', fontSize: 12 }}>{r.config_name || '—'}</td>
                  <td style={{ ...styles.td, fontSize: 12, color: '#6b7280' }}>
                    {r.generated_at ? new Date(r.generated_at).toLocaleDateString() : '—'}
                  </td>
                  <td style={styles.td}>{r.generated_by}</td>
                  <td style={{ ...styles.td, fontWeight: 700, textAlign: 'center' as const }}>{r.student_count}</td>
                  <td style={{ ...styles.td, fontWeight: 700, textAlign: 'center' as const }}>{r.questions_per_student}</td>
                  <td style={styles.td}>
                    <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                      <button
                        style={styles.actionBtn}
                        title="Export Student PDFs"
                        onClick={() => exportAssessmentPDF(r.id)}
                      >
                        <Download size={13} />
                        <span style={{ fontSize: 11 }}>PDFs</span>
                      </button>
                      <button
                        style={{ ...styles.actionBtn, color: '#4f46e5' }}
                        title="Export Answer Key"
                        onClick={() => exportAnswerKey(r.id)}
                      >
                        <Download size={13} />
                        <span style={{ fontSize: 11 }}>Keys</span>
                      </button>
                      {confirmDelete === r.id ? (
                        <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
                          <input
                            style={styles.passphraseInput}
                            type="password"
                            placeholder="Passphrase"
                            value={passphrase}
                            onChange={e => setPassphrase(e.target.value)}
                            onKeyDown={e => e.key === 'Enter' && handleDelete(r.id)}
                          />
                          <button
                            style={{ ...styles.actionBtn, color: '#dc2626', fontSize: 11 }}
                            disabled={deletingId === r.id}
                            onClick={() => handleDelete(r.id)}
                          >
                            {deletingId === r.id ? '…' : 'Confirm'}
                          </button>
                          <button
                            style={{ ...styles.actionBtn, fontSize: 11 }}
                            onClick={() => { setConfirmDelete(null); setPassphrase('') }}
                          >
                            Cancel
                          </button>
                        </div>
                      ) : (
                        <button
                          style={{ ...styles.actionBtn, color: '#dc2626' }}
                          title="Delete assessment"
                          onClick={() => setConfirmDelete(r.id)}
                        >
                          <Trash2 size={13} />
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}

const styles: Record<string, React.CSSProperties> = {
  empty: {
    background: 'rgba(255,255,255,0.6)',
    backdropFilter: 'blur(14px)', WebkitBackdropFilter: 'blur(14px)',
    border: '1px solid rgba(255,255,255,0.65)',
    borderRadius: 14, padding: '40px 24px',
    textAlign: 'center' as const, color: '#9ca3af', fontSize: 14,
  },
  tableWrap: {
    background: 'rgba(255,255,255,0.6)',
    backdropFilter: 'blur(14px)', WebkitBackdropFilter: 'blur(14px)',
    border: '1px solid rgba(255,255,255,0.65)',
    borderRadius: 14, overflow: 'auto',
  },
  table: { width: '100%', borderCollapse: 'collapse' as const, fontSize: 13 },
  thead: { background: 'rgba(249,250,251,0.8)' },
  th: {
    padding: '10px 14px', textAlign: 'left' as const,
    fontSize: 11, fontWeight: 700, color: '#6b7280',
    textTransform: 'uppercase' as const, letterSpacing: 0.4,
    borderBottom: '1px solid #f3f4f6',
  },
  tr: { borderBottom: '1px solid #f3f4f6' },
  td: { padding: '12px 14px', color: '#374151', verticalAlign: 'middle' as const },
  actionBtn: {
    display: 'flex', alignItems: 'center', gap: 4,
    padding: '5px 10px', border: '1px solid #e5e7eb',
    borderRadius: 7, background: 'none', cursor: 'pointer',
    fontSize: 13, color: '#4b5563',
  },
  passphraseInput: {
    padding: '5px 10px', border: '1px solid #e5e7eb',
    borderRadius: 7, fontSize: 12, width: 120,
  },
}
