import { useState, useEffect } from 'react'
import { RefreshCw } from 'lucide-react'
import toast from 'react-hot-toast'
import { listAssessmentHistory } from '../../api'
import { errorMessage } from '../../api/errors'
import { usePagination } from '../../components/Paginator'

/**
 * A read-only record of what has been generated.
 *
 * This tab acquired exports, a passphrase field and a delete, and became the
 * most actionable screen in the module while being the one nobody comes to in
 * order to DO something. Acting belongs where the assessment is already
 * selected — Sessions — so the papers and answer-key downloads moved there and
 * the delete went entirely. What is left answers one question: what did we
 * issue, to whom, and where has it got to.
 */
interface AssessmentRecord {
  id: number
  assessment_name: string
  config_name: string | null
  student_count: number
  questions_per_student: number
  generated_by: string
  generated_at: string | null
  batch_name: string | null
  /** null means the paper uses the platform default. */
  pass_threshold: number | null
  status_counts?: { pending: number; in_progress: number; submitted: number; expired: number }
}

const PAGE_SIZE = 20

export function AssessmentHistoryView() {
  const [records, setRecords] = useState<AssessmentRecord[]>([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')

  function load() {
    setLoading(true)
    listAssessmentHistory()
      .then(setRecords)
      .catch(e => toast.error(errorMessage(e, 'Failed to load history')))
      .finally(() => setLoading(false))
  }

  useEffect(() => { load() }, [])

  const q = search.trim().toLowerCase()
  const visible = q
    ? records.filter(r => `${r.assessment_name} ${r.batch_name || ''} ${r.generated_by}`
        .toLowerCase().includes(q))
    : records

  // The list only grows. Search finds a named paper; paging keeps the rest off
  // the screen without hiding it.
  const { pageData, Paginator } = usePagination(visible, PAGE_SIZE)

  if (loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', padding: 60 }}>
        <RefreshCw size={18} style={{ animation: 'spin 1s linear infinite', color: '#6b7280' }} />
      </div>
    )
  }

  return (
    <div>
      {/* Above the table, so a search that matches nothing keeps the box that
          would clear it. */}
      {records.length > 0 && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12, flexWrap: 'wrap' }}>
          <input
            value={search}
            onChange={e => setSearch(e.target.value)}
            onKeyDown={e => { if (e.key === 'Escape') setSearch('') }}
            placeholder="Find by name, batch, or who generated it…"
            autoComplete="off"
            name="history-search"
            style={{ padding: '7px 11px', borderRadius: 8, border: '1px solid #e5e7eb', fontSize: 12, minWidth: 260 }}
          />
          <span style={{ fontSize: 11, color: '#6b7280' }}>
            {q ? `${visible.length} of ${records.length}` : `${records.length} assessment${records.length === 1 ? '' : 's'}`}
          </span>
          <button style={styles.refreshBtn} onClick={load} title="Reload">
            <RefreshCw size={13} /> Refresh
          </button>
        </div>
      )}

      {records.length === 0 ? (
        <div style={styles.empty}>No assessments generated yet. Go to Generate tab to create your first assessment.</div>
      ) : visible.length === 0 ? (
        <div style={styles.empty}>No assessment matches “{search}”.</div>
      ) : (
        <>
          <div style={styles.tableWrap}>
            <table style={styles.table}>
              <thead>
                <tr style={styles.thead}>
                  {['Name', 'Batch', 'Date', 'Generated By', 'Coders', 'Questions', 'Pass mark', 'Progress'].map(h => (
                    <th key={h} style={styles.th}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {pageData.map(r => (
                  <tr key={r.id} style={styles.tr}>
                    <td style={{ ...styles.td, fontWeight: 700 }}>{r.assessment_name}</td>
                    <td style={{ ...styles.td, color: '#6b7280', fontSize: 12 }}>{r.batch_name || '—'}</td>
                    <td style={{ ...styles.td, fontSize: 12, color: '#6b7280' }}>
                      {r.generated_at ? new Date(r.generated_at).toLocaleDateString() : '—'}
                    </td>
                    <td style={styles.td}>{r.generated_by}</td>
                    <td style={{ ...styles.td, fontWeight: 700, textAlign: 'center' as const }}>{r.student_count}</td>
                    <td style={{ ...styles.td, fontWeight: 700, textAlign: 'center' as const }}>{r.questions_per_student}</td>
                    <td style={{ ...styles.td, textAlign: 'center' as const, fontSize: 12, color: '#6b7280' }}>
                      {r.pass_threshold != null ? `${r.pass_threshold}%` : 'default'}
                    </td>
                    {/* Where it stands, so the list answers "is this finished?"
                        without opening Sessions to find out. */}
                    <td style={{ ...styles.td, fontSize: 11, whiteSpace: 'nowrap' as const }}>
                      {(() => {
                        const c = r.status_counts
                        if (!c) return <span style={{ color: '#9ca3af' }}>—</span>
                        const done = c.submitted, waiting = c.pending + c.in_progress
                        return (
                          <span>
                            <strong style={{ color: done ? '#15803d' : '#9ca3af' }}>{done} done</strong>
                            {waiting > 0 && <span style={{ color: '#92400e' }}> · {waiting} waiting</span>}
                            {c.expired > 0 && <span style={{ color: '#b91c1c' }}> · {c.expired} expired</span>}
                          </span>
                        )
                      })()}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <Paginator />
          <div style={{ fontSize: 11, color: '#9ca3af', marginTop: 10 }}>
            A read-only record. Papers, the answer key and per-question responses download from the Sessions tab.
          </div>
        </>
      )}
    </div>
  )
}

const styles: Record<string, React.CSSProperties> = {
  empty: {
    background: 'rgba(255,255,255,0.6)',
    backdropFilter: 'blur(14px)', WebkitBackdropFilter: 'blur(14px)',
    border: '1px solid rgba(255,255,255,0.65)',
    borderRadius: 14, padding: '40px 24px',
    textAlign: 'center' as const, color: '#9ca3af', fontSize: 14,
  },
  tableWrap: {
    background: 'rgba(255,255,255,0.6)',
    backdropFilter: 'blur(14px)', WebkitBackdropFilter: 'blur(14px)',
    border: '1px solid rgba(255,255,255,0.65)',
    borderRadius: 14, overflow: 'auto',
  },
  table: { width: '100%', borderCollapse: 'collapse' as const, fontSize: 13 },
  thead: { background: 'rgba(249,250,251,0.8)' },
  th: {
    padding: '10px 14px', textAlign: 'left' as const,
    fontSize: 11, fontWeight: 700, color: '#6b7280',
    textTransform: 'uppercase' as const, letterSpacing: 0.4,
    borderBottom: '1px solid #f3f4f6',
  },
  tr: { borderBottom: '1px solid #f3f4f6' },
  td: { padding: '12px 14px', color: '#374151', verticalAlign: 'middle' as const },
  refreshBtn: {
    display: 'flex', alignItems: 'center', gap: 5,
    padding: '6px 12px', border: '1px solid #e5e7eb',
    borderRadius: 8, background: '#fff', cursor: 'pointer',
    fontSize: 12, fontWeight: 600, color: '#4b5563',
  },
}
